# Generated by Django 2.2.9 on 2020-01-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200118_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('P', 'Popular'), ('D', 'Discount')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
            options={
                'unique_together': {('item', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attachment', models.ImageField(blank=True, upload_to='')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Variant')),
            ],
            options={
                'unique_together': {('variant', 'value')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_variants',
            field=models.ManyToManyField(to='core.ItemVariant'),
        ),
    ]
