# Generated by Django 2.2.9 on 2020-01-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200131_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_unit',
            new_name='unit',
        ),
    ]
